### PR TITLE
Fix OT reconciliation desync and feedback loop

### LINKED ISSUE #151: Desync, with feedback loop issues
Extension Version 1.5.11
Setup:
1. User A - VSCode
2. User B - Online IDE
3. User C - VSCode

User A has edited code using an agent, while User C was opening the project.
User B observed that changes to some methods from agent execution by User A was not present.

Further attempt to modify code lead to feedback loop and some issues visible on the video, made by User A.

Likely culprit: somewhere code is modified directly, instead of through OT operations. As mentioned before, any direct modifications to code should not happen ever when working with OT. Code modifications should only occur through creation and execution of OT Operations, so any conflicts are auto-resolved by OT system.

Video is shared privately with @kpal81xd

### PR DESCRIPTION
**Pull request by kpal81xd**
Closes #151

## Summary

- **Root cause**: During rapid remote op bursts, `OTDocument._text` advances synchronously while VS Code's buffer updates asynchronously. Reconciliation was diffing against the raced-ahead `_text`, producing inverse ops that undid queued remote ops — causing missing changes and feedback loops.
- **Fix**: Diff against the emission-time content snapshot (`content` param) instead of live `_text`. When canonical state has advanced past the snapshot, transform the recovered user keystrokes against the advancement via `ot-text.transform()` to keep positions valid.
- **Refactor**: Extract `diffOp(from, to)` utility to deduplicate the minimalDiff-to-ShareDbTextOp pattern across `disk.ts` and `project-manager.ts`.

## Test plan

- [x] `npm run compile` — clean
- [x] `npm run lint` — clean
- [x] `npm run pretest` — clean
- [x] Manual: rapid agent edits in VSCode while another user observes in online IDE — changes arrive without inversion or feedback loop
- [x] Regression: single remote op with user typing during async gap still recovers keystrokes

### CODE REVIEW

File: src/disk.ts [hunk 1]
```diff
@@ -297,43 +299,42 @@ class Disk extends Linker<{ folderUri: vscode.Uri; projectManager: ProjectManage
                         const path = relativePath(uri, this._folderUri);
                         const file = this._projectManager.files.get(path);
                         if (file?.type === 'file') {
-                            const docText = file.doc.data;
+                            const expectedText = buffer.toString(content);
```
Comment (Maksims) [inline src/disk.ts]: Does this happens on every edit, or only when saved?
If it happens often, was RAM checked for memory leaking and consumption on large files?
